services:
  - type: web
    name: docquery
    region: oregon
    plan: standard  # MUST specify paid tier
    buildCommand: |
      pip install -e . &&
      pip install --no-cache-dir transformers sentence-transformers faiss-cpu python-docx spacy &&
      python -m spacy download en_core_web_sm
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: $PORT
      - key: PYTORCH_ENABLE_MPS_FALLBACK
        value: 1