services:
  - type: web
    name: docquery
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PORT
        value: $PORT
    healthCheckPath: /_stcore/health
    plan: standard # Important for memory needs (1GB RAM minimum)