services:
  - type: web
    name: docquery
    region: oregon
    plan: starter  # Reduced from standard since no heavy ML dependencies
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: $PORT